;; This logfile was generated automatically by `xindy'
;; at 04.03.2019  18:01:14
;; Indexstyle: "/tmp/yNGGAaoal4", Rawindex: "/tmp/MCHxEsTQ3d", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "È»¼Ð" -> "P"
Letter-group: "à—" -> "D"
Letter-group: "»Ðæ" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à—" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»Ðæ" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È»¼Ð" -> "P"