;; This logfile was generated automatically by `xindy'
;; at 04.03.2019  11:50:31
;; Indexstyle: "/tmp/BYrFBSb28T", Rawindex: "/tmp/DT6zTn3rN6", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "È»¼Ð" -> "P"
Letter-group: "à—" -> "D"
Letter-group: "»Ðæ" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à—" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»Ðæ" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È»¼Ð" -> "P"