;; This logfile was generated automatically by `xindy'
;; at 07.03.2019  13:39:09
;; Indexstyle: "/tmp/TzwAfmnlil", Rawindex: "/tmp/jXoD78x9MJ", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "†ËÈ" -> "C"
Letter-group: "æ€105" -> "W"
Letter-group: "´—»" -> "L"
Letter-group: "€¼ÐíÐ" -> "A"
Letter-group: "††¨" -> "C"
Letter-group: "à—" -> "D"
Letter-group: "È»¼Ð" -> "P"
Letter-group: "»Ðæ" -> "M"
Letter-group: "ÚÈ†" -> "T"
Letter-group: "´€ËÚÈ†" -> "D"
Letter-group: "È†„" -> "P"
Letter-group: "´€Ð" -> "L"
Letter-group: "€Ê" -> "D"
Letter-group: "—Ú¤ð" -> "E"
Letter-group: "œË4" -> "F"
Letter-group: "†—€" -> "C"
Letter-group: "†—Ë¼" -> "C"
Letter-group: "¨Ëœà" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€¼ÐíÐ" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "††¨" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€Ê" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "—Ú¤ð" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œË4" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨Ëœà" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´€Ð" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»Ðæ" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È†„" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÚÈ†" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "æ€105" -> "W"